### ISSUE TITLE
Feature 999: Venue display

### ISSUE THREAD

**Issue by edwery** [u3a-siteworks-development/u3a-siteworks-core#25]
This relates to: 

<https://project.u3awp.uk/projects/testing/work_packages/999>

On the Production/live version, when you select a venue, the page gives a list of Events that reference the venue and also Groups which use this venue.

It would be desirable if the 2 items were separated ie Events and then Groups.

**Comment by mike99christie** [comment]
The code for this is in function find_xrefs in trait ManageCrossRefs andshould be easy to implement. :-)

**Comment by edwery** [comment]
I've got a fix coded,just need to test it

**Comment by edwery** [comment]
#28  Is the PR for this
