### ISSUE TITLE
u3a group list - change heading in properties panel

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#40]
Suggest that the heading should be something like "Display options" rather than "Sort Style" as the choices are not just about sort order.
![image](https://github.com/u3a-siteworks-development/u3a-siteworks-core/assets/34215865/55cb323a-2e8b-4ec2-b894-457ee99573f6)

**Comment by mike99christie** [comment]
Display options seems good to me.
