### ISSUE TITLE
OP1024 Allow groups to be assigned to multiple categories

### ISSUE THREAD

**Issue by mike99christie** [u3a-siteworks-development/u3a-siteworks-core#48]
This is a proposal I put on Slack on 13 February
I'd like to allow groups to be assigned to multiple "group categories".
 and then add an option on the grouplist block to display only the groups in a specific category, as we already do for "event category". This would allow a u3a to set up a category such as "newly formed" and then use a grouplist block to display only the groups in that category. This would automate the list that some Siteworks u3as already create manually. There are lots of other uses for this, for example, it would provide an alternative solution for those u3as that want to add new status values instead. Another example, add categories for those groups that meet in specific areas (see Exmouth u3a wishes) and list all the groups that meet in a specific area.
Phips correctly points out that we could use the built-in WordPress categories for this, but I think that having two sorts of categories would make the editing UI more complex.
Perhaps we could also all events to belong to more than one "Event category" though I can see few benefits for that.
The code to do this is very simple. it is a one liner in field_descriptions to allow multiple values, plus the code to extend grouplist in a similar way to the existing option for eventlist

I'd like to get this put to Change Board to get it into release 1.1!!
in OpenProject FEATURE #1024

**Comment by Windsurfer01** [comment]
I think that is a good idea. It is what we do.

**Comment by mike99christie** [comment]
I have implemented this in branch mc-OP1024.
This includes an option in the grouplist block to choose a single group category.
In this case the list will just display a heading and then the groups in that category. In this case the 'sort' attribute is irrelevant and is hidden in the block settings.
In the metabox to edit a group's data, you can select more than one category. Under that box it says:
         You may enter more than one category here.
