### ISSUE TITLE
event properties panel - wording for event grid layout

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#69]
![event-list-options](https://github.com/u3a-siteworks-development/u3a-siteworks-core/assets/34215865/eb8c615a-471e-405e-8f55-671b3f233c13)

Suggest that the wording for the grid layout option should be

**Grid with featured image**
instead of
**Grid with image.**

I think this makes it clearer what image will be used rather than leaving the WM to hunt for an event image setting.

**Comment by mike99christie** [comment]
Good suggestion.
