### ISSUE TITLE
u3a event list heading does not show selected category

### ISSUE THREAD

**Issue by edwery** [u3a-siteworks-development/u3a-siteworks-core#75]
Relates to:
https://project.u3awp.uk/projects/testing/work_packages/1034/

**Comment by edwery** [comment]
I have put some tentative code in core on branch es-1034 - if that helps

**Comment by mike99christie** [comment]
My issue is that I don't think that adding the category name to the H3 element is always suitable.
I have a page about monthly Meetings and an event category "Monthly Meeting" on which there are two eventlist blocks, the first showing "Forthcoming events" and the other other showing "Previous events". It would be odd to include the words "Monthly Meeting" after those since this is the Monthly Meetings page.

**Comment by edwery** [comment]
I can see that wouldn't look right. Equally, I think the 'options' pane could be getting too full, so dont think making this optional is right either. Perhaps push back to see if its really needed?

**Comment by mike99christie** [comment]
The issue arose from [(https://u3awebdev.org.uk/viewtopic.php?t=464)] where multiple eventlists each for a different category are shown on the same page.
My **preferred** solution/work-around would be for the page's editor to add an extra heading block above each list. Not ideal, as this leads to one heading above another.
The alternative would be to allow the editor to choose multiple categories in the filter options for the eventlist, but this adds quite a lot of complexity for a little needed use case, but to continue not to identify the categories in the list heading, and to continue to sort them only by date.
Note that if one filter events to only show events in the next/last 90 days, say, the heading does not say what limit is on the events shown. I think this is the best approach.

**Comment by nicktrosnant** [comment]
Rather like the solution we implemented for the Notices list heading, perhaps it provides the most flexibility if we just put a switch to disable the title so the WM can add their own choice of heading if the default does not suit?
![image](https://github.com/u3a-siteworks-development/u3a-siteworks-core/assets/34215865/c4de28b6-7b88-4ea4-a103-12bf390a73b0)

**Comment by mike99christie** [comment]
That sound like a solution that is pretty simple to implement, without making the block attributes pane too complicated. I'm happy to go with that.
I think we should use a y/n string attribute for this but use a toggle switch, as the latest version does for "crop".

**Comment by edwery** [comment]
added PR for the change suggested.
