### ISSUE TITLE
OP1041 - validation on start/end times for groups and events

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#78]
It is possible to enter end times earlier than start times (and vice versa).
Further validation needed on these time fields.

**Comment by mike99christie** [comment]
I'm inclined to say "caveat emptor"!
It is harder to do cross field validation before the data is sent to the server, by which time it is too late, and no page on which to report the problem!
Cross field validation on the client side would require some complex bespoke Javascript to be created and downloaded. I think I know how to do this but is it really worth it?
e.g. for download:
add_action('rwmb_enqueue_scripts',function()....)

**Comment by nicktrosnant** [comment]
Agreed "will not fix".
