### ISSUE TITLE
OP1046 u3a group list properties panel does not initially show Sort Order option

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#81]
The Display Options section of the properties panel should show a SORT ORDER option, but this does not initially appear.  It only appears if you set CATEGORY to a single category then back to "All categories".

![image](https://github.com/u3a-siteworks-development/u3a-siteworks-core/assets/34215865/42517a97-f568-4e9d-8cc2-d8bcc3e7704f)

The logic that sets up the visible properties in the panel needs checking.

**Comment by mike99christie** [comment]
line 136 of u3a-group-blocks.js should allow for the variable cat being undefined like so
    { show:('all' == cat || undefined === cat),

I'm rather busy with other priorities, and a bit unwell, so won't implement this myself!
PS I'm on holiday from Friday for a week.

**Comment by edwery** [comment]
I defaulted the cat to 'all' in a PR on main
