### ISSUE TITLE
OP1048 Undefined array key "venue" using filtered group list

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#83]
Report from OP1048:

Set u3a settings > Groups tab > radio button filtered
Use shortcode [u3agrouplist venue="y"] 
Display page and click on a letter
Errors Warning: Undefined array key "venue" in C:\Us.....\wp-content\plugins\u3a-siteworks-core\classes\class-u3a-group.php on line 1040
Around line 815 need to initialise $display_args['Venue'] with a default 'y' or 'n'

**Comment by mike99christie** [comment]
Just two comments about our procedures.
1) when creating an issue please assign it to the project "siteworks Development Team Planning and give the default status "No status".
2) I found it hard to identify which requirement had added the option to show venue in group lists. I found it as PR#66, and eventually found it was in OP1023 (Closed) Should we always create an issue as well as an OP item, and always have an issue for pull requests? That way Github would have a rationale log for all implemented changes. Or am I adding unnecessary overheads to the maintenance work?
