### ISSUE TITLE
OP1043 Venue page shows list of events at the venue but with no indication of whether they are past or future events.  

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#85]
[OP1043](https://project.u3awp.uk/projects/testing/work_packages/1043/activity)
Waiting for specification from Change Board as to what should be displayed

**Comment by nicktrosnant** [comment]
Discussed at Change Board 5th July 2024.

Agreed: The requirement is ti continue to show events but only show future events, and include the event date

**Comment by edwery** [comment]
The original requirement for this list was to show an administrator which events should be deleted if a venue is to be deleted. 
As we have shown the list to  all users, a new requirement has been formed that the normal user wants to see only events which are in the future.
To cover both those needs, I have sorted the list of events in date order, and shown all of them if the current user is an administrator, but only future ones if the current user is anyone else. 
I have also appended the date on which the event takes place to the text, as it seems remiss to have it available and not show it.
