### ISSUE TITLE
OP1054 Make featured images in the u3a event list grid view a clickable link

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-core#91]
proposed [on the forum](https://u3awpdev.org.uk/viewtopic.php?t=498)

In an ordinary query loop of posts it is possible to make the featured image (as well as the title) have a link to the post.  Some people seem more willing to click on images than a title in blue.
In the new grid format, could the featured image of the event have the same link as the title of the event?   (If this were an option I would always choose it, so from my point of view it could just be the standard.)

**Comment by mike99christie** [comment]
That seems a good idea and we should probably have done so from the start. It is an easy and very small mod to the code of function display_event_listing.

**Comment by mike99christie** [comment]
implemented and merged into main.
